### ISSUE TITLE
Incorrect Hyperlink in the Wallpapers Page

### ISSUE THREAD

**Issue by Jery-A** [RiiConnect24/Site#12]
The hyperlink for "Wallpaper Quote 3" is incorrect.
It currently leads to "Wallpaper Quote 4" instead of "Wallpaper Quote 3".

Here's the page I'm talking about:
https://rc24.xyz/goodies/wallpapers/

PS: I believe the problem is in line 137 of your html code.

**Comment by KcrPL** [comment]
![Thanks](http://i.imgur.com/vU78SNP.gif)

Thanks for reporting the problem, it has been fixed. **However**, it will not be up on the site right now because we have to wait for someone to pull the changes from GitHub (the change that I made) to the server.

Thanks again :)
