### ISSUE TITLE
Bug in goodies

### ISSUE THREAD

**Issue by Fun4TubeGr** [RiiConnect24/Site#20]
I have this issue why that is happend https://youtu.be/_Z-xfMx9dTg

**Comment by KcrPL** [comment]
This has been already fixed yesterday.

We uploaded the images and it's not working correctly. 
Here you can see more information about that: https://github.com/RiiConnect24/Site/commit/2a80e3a55c21bff21bf98b45313c8d3ca901203c

Have a nice day :)

**Comment by Fun4TubeGr** [comment]
Ok
