### ISSUE TITLE
EVC page wrong

### ISSUE THREAD

**Issue by ArtutoGamer** [RiiConnect24/Site#3]
Hi, I just found a bug on the Mexico Spanish EVC Results 

https://rc24.xyz/goodies/vote/036_spanish_results.php

The title should say "Everybody Votes Channel - Mexico **_Spanish_** Results" instead of "Everybody Votes Channel - Mexico **_French_** Results" 

And BTW, there's some other bugs which IDK if they can be fixed but hey.

First, on Spanish we start a question with ¿ and ends with ?
Second, here are some translations:

Detailed Results: = Resultados Detallados

Results by Gender.    =.  Resultados por género:
Male = Masculino
Female = Femenino
National Prediction Accuracy = Precisión Nacional de Predicción.

Hope you can fix this.

**Comment by larsenv** [comment]
I fixed the title, but I don't want to fix all the text right now.
