### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by XxXTommyXxX** [RiiConnect24/Site#34]
We should start using this icons in rc24.xyz sidenav. They are pretty!

https://material.io/tools/icons/?style=baseline

**Comment by KcrPL** [comment]
This is not an issue.

**Comment by larsenv** [comment]
I didn't get a chance to respond to this, [Materialize CSS has some icons](https://materializecss.com/icons.html) but we use [Font Awesome](https://fontawesome.com/) because it's, well, awesome!
