### ISSUE TITLE
Change current DNS to NextDNS (Add tutorial)

### ISSUE THREAD

**Issue by wuniversales** [RiiConnect24/Site#56]
I have seen that you have to change the DNS of the wii, the truth is that I prefer to use the DNS of "nextdns.io" since it blocks the advertising of the console, and allows me to configure the DNS to my liking ...

I would like to know how to configure RiiConnect24 using "NextDNS".

This dns allows you to change the IPs of the desired domains ...
In theory this DNS could be used instead of the one indicated on the web, just change the IPs of the specific URLs.

Could you add a tutorial on how to do it?

https://nextdns.io/

Thank you

**Comment by DismissedGuy** [comment]
If you want to use NextDNS on your Wii, I would recommend setting it as your secondary DNS (so replace 1.1.1.1 or 8.8.8.8). That way, you'd still be able to use the ad blocking capabilities and specify your own custom records if you'd want. If you however, for some reason don't feel like using RC24's DNS servers, you could use [this list of A-records](https://github.com/RiiConnect24/DNS-Server/blob/master/dns_zones.json) and configure your zones in NextDNS to follow that file. Set NextDNS as your primary DNS in that case. You'll have to update your configuration yourself if RC24 ever decides to add, remove or change a record, even though that may not happen too often.

I personally don't think a site webpage should be added for this, as very little people would actually want to configure their DNS like you do. But I'm not the one to judge about that.

**Comment by larsenv** [comment]
No, we will not add a tutorial. Never heard of NextDNS.

**Comment by KcrPL** [comment]
First DNS is ours, if your Wii want's to connect to our services, it does - it it wants to connect to something outside, it falls back to the secondary DNS - this is your choice. You can set it to whatever you want.
