### ISSUE TITLE
you should probably add the GNU mascot in ASCII

### ISSUE THREAD

**Issue by Abequinn** [RiiConnect24/Site#8]
because why not

**Comment by larsenv** [comment]
"Why not?" It's a waste of space.

It's ugly imo too.

**Comment by KcrPL** [comment]
Hmm. Why not :P 
@larsenv I'm ugly too, high five XD

**Comment by Abequinn** [comment]
XD

**Comment by KcrPL** [comment]
![GNU Mascot](https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Heckert_GNU_white.svg/1048px-Heckert_GNU_white.svg.png)
<3 XD, cool mascot

**Comment by Abequinn** [comment]
XD

**Comment by thejsa** [comment]
This unnecessarily uses up visitors' bandwidth or will be removed by CloudFlare's minification, so I see no point in including this.

**Comment by KcrPL** [comment]
@thejsa He's probably talking about the ASCII mascot in IOS Patcher that i host here. I'm hosting it here so users can auto update IOS patcher.

https://github.com/RiiConnect24/Site/tree/master/Patchers_Auto_Update/IOS-Patcher

**Comment by thejsa** [comment]
Should be moved to RiiConnect24/IOS-Patcher issues
