### ISSUE TITLE
Wii Mail Status Page - Internet Channel is partially working.

### ISSUE THREAD

**Issue by KcrPL** [RiiConnect24/Site#9]
On site it says: 
![Site screenshot](https://user-images.githubusercontent.com/17184296/29562946-cea0420c-873b-11e7-826c-8e0224489188.PNG)
That is true, however sometimes we can send Mails with link but sometimes it gives us error **102032**. I suggest to change it to `Partially working`

>Proof

![Working](http://i.imgur.com/vQht4Ni.png)
(**Sometimes working**)

![Not working](http://i.imgur.com/tnH9uYml.jpg)
(**And sometimes not working**)

**Comment by larsenv** [comment]
Even if a game gives 102032, it still will be set to "working" on the list.

Closing this.

**Comment by KcrPL** [comment]
👍
